title: Herman Barrantes
description: “I’m not a great programmer; I’m just a good programmer with great habits.” ― Kent Beck
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
